Repository nightscout/cgm-remote-monitor, pull requests merged in 2018-11, with the labels that each got.

#4060 Add CGM Sensor Stop
  lib/language.js
  lib/plugins/careportal.js
Labels: enhancement

#4088 Fix devicestatus and treatments id delete
  lib/server/activity.js
  lib/server/devicestatus.js
  lib/server/food.js
  lib/server/profile.js
  lib/server/treatments.js
  lib/server/websocket.js
Labels: bug

#4044 redirect HTTP to HTTPS unless explicitly instructed not to do this re…
  README.md
  app.js
  npm-shrinkwrap.json
  package.json
Labels: feature/security
