Repository nightscout/cgm-remote-monitor, pull requests merged in 2019-10, with the labels that each got.

#5043 Remote Loop overrides
  README.md
  app.js
  lib/api/index.js
  lib/api/notifications-v2.js
  lib/api/verifyauth.js
  lib/client/careportal.js
  lib/client/chart.js
  lib/client/renderer.js
  lib/plugins/loop.js
  lib/server/bootevent.js
  lib/server/loop.js
  lib/server/pushnotify.js
  npm-shrinkwrap.json
  package.json
Labels: aps-loop, enhancement, feature/careportal

#5123 fix: Fix value caching in the profile functions.
  lib/plugins/cob.js
  lib/profilefunctions.js
Labels: bug-fix

#5109 Make failing tests fail
  Makefile
  npm-shrinkwrap.json
  package.json
Labels: bug, bug-fix, quality assurance

#5081 D3 upgrade (library for visualizing data such as main view, graphs, etc.)
  lib/client/chart.js
  lib/client/index.js
  lib/client/renderer.js
  lib/plugins/pluginbase.js
  lib/report_plugins/calibrations.js
  lib/report_plugins/daytoday.js
  lib/report_plugins/weektoweek.js
  npm-shrinkwrap.json
  package.json
Labels: help wanted, library-update, needs testing
