Repository nightscout/cgm-remote-monitor, pull requests merged in 2025-05, with the labels that each got.

#8220 hide tooltip by display attribute instead of opacity
  lib/client/browser-utils.js
  lib/client/index.js
  lib/client/renderer.js
  lib/plugins/pluginbase.js
  lib/report_plugins/daytoday.js
  lib/report_plugins/weektoweek.js
Labels: ready

#8093 update readme link to maker plugin doc
  README.md
Labels: docs

#8346 New Crowdin updates
  translations/fr_FR.json
Labels: language translation
